const data = [
  { file: 'audio/stride.mp3', english: 'stride', russian: 'шагать' },
  { file: 'audio/strike.mp3', english: 'strike', russian: 'ударить, бить, бастовать' },
  { file: 'audio/string.mp3', english: 'string', russian: 'нанизать, натянуть' },
  { file: 'audio/strip.mp3', english: 'strip', russian: 'обнажать' },
  { file: 'audio/stript, stripped.mp3', english: 'stript, stripped', russian: 'обнажать' },
  { file: 'audio/strive.mp3', english: 'strive', russian: 'стараться' },
  { file: 'audio/striven, strived.mp3', english: 'striven, strived', russian: 'стараться' },
  { file: 'audio/strode, strided.mp3', english: 'strode, strided', russian: 'шагать' },
  { file: 'audio/strove, strived.mp3', english: 'strove, strived', russian: 'стараться' },
  { file: 'audio/struck, stricken.mp3', english: 'struck, stricken', russian: 'ударить, бить, бастовать' },
  { file: 'audio/struck.mp3', english: 'struck', russian: 'ударить, бить, бастовать' },
  { file: 'audio/strung, stringed.mp3', english: 'strung, stringed', russian: 'нанизать, натянуть' },
  { file: 'audio/stuck, sticked.mp3', english: 'stuck, sticked', russian: 'уколоть, приклеить' },
  { file: 'audio/stung, stang.mp3', english: 'stung, stang', russian: 'ужалить' },
  { file: 'audio/stung.mp3', english: 'stung', russian: 'ужалить' },
  { file: 'audio/stunk.mp3', english: 'stunk', russian: 'вонять' },
  { file: 'audio/sung.mp3', english: 'sung', russian: 'петь' },
  { file: 'audio/sunk.mp3', english: 'sunk', russian: 'опускаться, погружаться, тонуть' },
  { file: 'audio/swam.mp3', english: 'swam', russian: 'плыть' },
  { file: 'audio/swang.mp3', english: 'swang', russian: 'качаться' },
  { file: 'audio/swear.mp3', english: 'swear', russian: '(по)клясться, присягнуть' },
  { file: 'audio/sweat, sweated.mp3', english: 'sweat, sweated', russian: '' },
  { file: 'audio/sweat.mp3', english: 'sweat', russian: 'потеть' },
  { file: 'audio/sweep.mp3', english: 'sweep', russian: 'мести, промчаться' },
  { file: 'audio/swell.mp3', english: 'swell', russian: 'вздуться' },
  { file: 'audio/swelt, swole, swoll, swelled.mp3', english: 'swelt, swole, swoll, swelled', russian: 'вздуться, набухать' },
  { file: 'audio/swelt.mp3', english: 'swelt', russian: 'вздуться, набухать' },
  { file: 'audio/swept, sweeped.mp3', english: 'swept, sweeped', russian: 'мести, промчаться' },
  { file: 'audio/swim.mp3', english: 'swim', russian: 'плыть' },
  { file: 'audio/swing.mp3', english: 'swing', russian: 'качаться' },
  { file: 'audio/swollen, swelled.mp3', english: 'swollen, swelled', russian: 'вздуться, вздуться' },
  { file: 'audio/swore.mp3', english: 'swore', russian: '(по)клясться, присягнуть' },
  { file: 'audio/sworn.mp3', english: 'sworn', russian: '(по)клясться, присягнуть' },
  { file: 'audio/swum.mp3', english: 'swum', russian: 'плыть' },
  { file: 'audio/swung.mp3', english: 'swung', russian: 'качаться' },
  { file: 'audio/take.mp3', english: 'take', russian: 'взять, брать' },
  { file: 'audio/taken.mp3', english: 'taken', russian: 'взять, брать' },
  { file: 'audio/taught.mp3', english: 'taught', russian: 'учить' },
  { file: 'audio/teach.mp3', english: 'teach', russian: 'учить' },
  { file: 'audio/tear.mp3', english: 'tear', russian: 'рвать' },
  { file: 'audio/tell.mp3', english: 'tell', russian: 'рассказывать, сказать' },
  { file: 'audio/think.mp3', english: 'think', russian: 'думать' },
  { file: 'audio/thought.mp3', english: 'thought', russian: 'думать' },
  { file: 'audio/threw.mp3', english: 'threw', russian: 'бросить' },
  { file: 'audio/thrive.mp3', english: 'thrive', russian: 'процветать' },
  { file: 'audio/thriven, thrived.mp3', english: 'thriven, thrived', russian: 'процветать' },
  { file: 'audio/throve, thrived, thrave.mp3', english: 'throve, thrived, thrave', russian: 'процветать' },
  { file: 'audio/throve, thrived.mp3', english: 'throve, thrived', russian: 'процветать' },
  { file: 'audio/throw.mp3', english: 'throw', russian: 'бросить' },
  { file: 'audio/thrown.mp3', english: 'thrown', russian: 'бросить' },
  { file: 'audio/thrust, thrusted.mp3', english: 'thrust, thrusted', russian: 'толкнуть, сунуть' },
  { file: 'audio/thrust.mp3', english: 'thrust', russian: 'толкнуть, сунуть' },
  { file: 'audio/told.mp3', english: 'told', russian: 'рассказывать, сказать' },
  { file: 'audio/took.mp3', english: 'took', russian: 'взять, брать' },
  { file: 'audio/tore.mp3', english: 'tore', russian: 'рвать' },
  { file: 'audio/torn.mp3', english: 'torn', russian: 'рвать' },
  { file: 'audio/understand.mp3', english: 'understand', russian: 'понимать' },
  { file: 'audio/understood.mp3', english: 'understood', russian: 'понимать' },
  { file: 'audio/vex.mp3', english: 'vex', russian: 'досаждать' },
  { file: 'audio/vext, vexed.mp3', english: 'vext, vexed', russian: 'досаждать' },
  { file: 'audio/wake.mp3', english: 'wake', russian: 'просыпаться, будить' },
  { file: 'audio/was, were.mp3', english: 'was, were', russian: 'быть' },
  { file: 'audio/wax.mp3', english: 'wax', russian: 'вощить' },
  { file: 'audio/waxen, waxed.mp3', english: 'waxen, waxed', russian: 'вощить' },
  { file: 'audio/wear.mp3', english: 'wear', russian: 'носить(одежду)' },
  { file: 'audio/weave.mp3', english: 'weave', russian: 'ткать' },
  { file: 'audio/wed, wedded.mp3', english: 'wed, wedded', russian: 'вступать в брак' },
  { file: 'audio/wed.mp3', english: 'wed', russian: 'вступать в брак' },
  { file: 'audio/weep.mp3', english: 'weep', russian: 'плакать' },
  { file: 'audio/wend.mp3', english: 'wend', russian: 'идти' },
  { file: 'audio/went, wended.mp3', english: 'went, wended', russian: 'идти, уходить' },
  { file: 'audio/went.mp3', english: 'went', russian: 'идти, уходить' },
  { file: 'audio/wept, weeped.mp3', english: 'wept, weeped', russian: 'плакать' },
  { file: 'audio/wet, wetted.mp3', english: 'wet, wetted', russian: 'мочить, увлажнять' },
  { file: 'audio/wet.mp3', english: 'wet', russian: 'мочить, увлажнять' },
  { file: 'audio/wex, waxed.mp3', english: 'wex, waxed', russian: 'вощить' },
  { file: 'audio/win.mp3', english: 'win', russian: 'выиграть' },
  { file: 'audio/wind.mp3', english: 'wind', russian: 'наматывать' },
  { file: 'audio/woke.mp3', english: 'woke', russian: 'просыпаться, будить' },
  { file: 'audio/woken.mp3', english: 'woken', russian: 'просыпаться, будить' },
  { file: 'audio/won.mp3', english: 'won', russian: 'выиграть' },
  { file: 'audio/wore.mp3', english: 'wore', russian: 'носить(одежду)' },
  { file: 'audio/worn.mp3', english: 'worn', russian: 'носить(одежду)' },
  { file: 'audio/wound.mp3', english: 'wound', russian: 'наматывать' },
  { file: 'audio/wove.mp3', english: 'wove', russian: 'ткать' },
  { file: 'audio/woven.mp3', english: 'woven', russian: 'ткать' },
  { file: 'audio/wrang, wrung, wringed.mp3', english: 'wrang, wrung, wringed', russian: 'скрутить, сжать' },
  { file: 'audio/wreak.mp3', english: 'wreak', russian: 'посеять' },
  { file: 'audio/wring.mp3', english: 'wring', russian: 'скрутить, сжать' },
  { file: 'audio/write.mp3', english: 'write', russian: 'писать' },
  { file: 'audio/writhe.mp3', english: 'writhe', russian: 'корчить' },
  { file: 'audio/writhen, writhed.mp3', english: 'writhen, writhed', russian: 'корчить' },
  { file: 'audio/written.mp3', english: 'written', russian: 'писать' },
  { file: 'audio/wroke, wreaked.mp3', english: 'wroke, wreaked', russian: 'посеять' },
  { file: 'audio/wroken, wreaked.mp3', english: 'wroken, wreaked', russian: 'посеять' },
  { file: 'audio/wrote.mp3', english: 'wrote', russian: 'писать' },
  { file: 'audio/wrothe, writhed.mp3', english: 'wrothe, writhed', russian: 'корчить' },
  { file: 'audio/wrung, wringed.mp3', english: 'wrung, wringed', russian: 'скрутить, сжать' },
  { file: 'audio/ate.mp3', english: 'ate', russian: 'кушать, есть' },
  { file: 'audio/be (am, is, are).mp3', english: 'be (am, is, are)', russian: 'быть' },
  { file: 'audio/bear.mp3', english: 'bear', russian: 'родить' },
  { file: 'audio/beat.mp3', english: 'beat', russian: 'бить' },
  { file: 'audio/beaten.mp3', english: 'beaten', russian: 'бить' },
  { file: 'audio/became.mp3', english: 'became', russian: 'стать, сделаться' },
  { file: 'audio/become.mp3', english: 'become', russian: 'стать, сделаться' },
  { file: 'audio/been.mp3', english: 'been', russian: 'быть, являться' },
  { file: 'audio/began.mp3', english: 'began', russian: 'начать' },
  { file: 'audio/beget.mp3', english: 'beget', russian: 'рождать' },
  { file: 'audio/begin.mp3', english: 'begin', russian: 'начать' },
  { file: 'audio/begot.mp3', english: 'begot', russian: 'рождать' },
  { file: 'audio/begotten.mp3', english: 'begotten', russian: 'рождать' },
  { file: 'audio/begun.mp3', english: 'begun', russian: 'начать' },
  { file: 'audio/bend.mp3', english: 'bend', russian: 'согнуть(ся)' },
  { file: 'audio/bent.mp3', english: 'bent', russian: 'согнуть(ся)' },
  { file: 'audio/bereave.mp3', english: 'bereave', russian: '' },
  { file: 'audio/bereft, bereaved.mp3', english: 'bereft, bereaved', russian: 'скорбеть, отнимать, лиишать' },
  { file: 'audio/beseech.mp3', english: 'beseech', russian: 'умолять' },
  { file: 'audio/besought, beseeched.mp3', english: 'besought, beseeched', russian: 'умолять' },
  { file: 'audio/bet.mp3', english: 'bet', russian: 'держать пари' },
  { file: 'audio/bid.mp3', english: 'bid', russian: 'велеть, просить' },
  { file: 'audio/bidden, bided.mp3', english: 'bidden, bided', russian: '' },
  { file: 'audio/bide.mp3', english: 'bide', russian: 'выжидать' },
  { file: 'audio/bind.mp3', english: 'bind', russian: 'связать' },
  { file: 'audio/bit.mp3', english: 'bit', russian: 'кусать' },
  { file: 'audio/bite.mp3', english: 'bite', russian: 'кусать' },
  { file: 'audio/bitten.mp3', english: 'bitten', russian: 'кусать' },
  { file: 'audio/bled.mp3', english: 'bled', russian: 'кровоточить' },
  { file: 'audio/bleed.mp3', english: 'bleed', russian: 'кровоточить' },
  { file: 'audio/blew.mp3', english: 'blew', russian: 'дуть' },
  { file: 'audio/blow.mp3', english: 'blow', russian: 'дуть' },
  { file: 'audio/blown.mp3', english: 'blown', russian: 'дуть' },
  { file: 'audio/bode, bided.mp3', english: 'bode, bided', russian: 'выжидать' },
  { file: 'audio/bore.mp3', english: 'bore', russian: 'родить' },
  { file: 'audio/born, borne.mp3', english: 'born, borne', russian: 'родить' },
  { file: 'audio/bought.mp3', english: 'bought', russian: 'купить' },
  { file: 'audio/bound.mp3', english: 'bound', russian: 'связать' },
  { file: 'audio/break.mp3', english: 'break', russian: '(с)ломать' },
  { file: 'audio/bred.mp3', english: 'bred', russian: 'выращивать' },
  { file: 'audio/breed.mp3', english: 'breed', russian: 'выращивать' },
  { file: 'audio/bring.mp3', english: 'bring', russian: 'принести' },
  { file: 'audio/broadcast, broadcasted.mp3', english: 'broadcast, broadcasted', russian: 'распространять, разбрасывать' },
  { file: 'audio/broadcast.mp3', english: 'broadcast', russian: 'распространять, разбрасывать' },
  { file: 'audio/broke.mp3', english: 'broke', russian: '(с)ломать' },
  { file: 'audio/broken.mp3', english: 'broken', russian: '(с)ломать' },
  { file: 'audio/brought.mp3', english: 'brought', russian: 'принести' },
  { file: 'audio/build.mp3', english: 'build', russian: 'строить' },
  { file: 'audio/built.mp3', english: 'built', russian: 'строить' },
  { file: 'audio/burn.mp3', english: 'burn', russian: 'жечь, гореть' },
  { file: 'audio/burnt, burned.mp3', english: 'burnt, burned', russian: 'жечь, гореть' },
  { file: 'audio/burst.mp3', english: 'burst', russian: 'разразиться, взорваться' },
  { file: 'audio/bust, busted.mp3', english: 'bust, busted', russian: 'разжаловать' },
  { file: 'audio/bust.mp3', english: 'bust', russian: 'разжаловать' },
  { file: 'audio/buy.mp3', english: 'buy', russian: 'купить' },
  { file: 'audio/came.mp3', english: 'came', russian: 'прийти' },
  { file: 'audio/cast.mp3', english: 'cast', russian: 'кинуть, лить металл' },
  { file: 'audio/catch.mp3', english: 'catch', russian: 'ловить, поймать' },
  { file: 'audio/caught.mp3', english: 'caught', russian: 'ловить, поймать' },
  { file: 'audio/chid, chided.mp3', english: 'chid, chided', russian: 'журить, упрекать' },
  { file: 'audio/chidden, chided, chid.mp3', english: 'chidden, chided, chid', russian: '' },
  { file: 'audio/chide.mp3', english: 'chide', russian: 'журить, упрекать' },
  { file: 'audio/choose.mp3', english: 'choose', russian: 'выбрать' },
  { file: 'audio/chose.mp3', english: 'chose', russian: 'выбрать' },
  { file: 'audio/chosen.mp3', english: 'chosen', russian: 'выбрать' },
  { file: 'audio/clad, clothed.mp3', english: 'clad, clothed', russian: 'одевать, покрывать' },
  { file: 'audio/clad.mp3', english: 'clad', russian: 'одевать, покрывать' },
  { file: 'audio/clap.mp3', english: 'clap', russian: 'хлопать, хлопать в ладоши' },
  { file: 'audio/clapt, clapped.mp3', english: 'clapt, clapped', russian: 'хлопать, хлопать в ладоши' },
  { file: 'audio/cleave.mp3', english: 'cleave', russian: 'раскалывать, прокладывать себе путь' },
  { file: 'audio/cleft, cleaved.mp3', english: 'cleft, cleaved', russian: 'раскалывать, прокладывать себе путь' },
  { file: 'audio/cling.mp3', english: 'cling', russian: 'цепляться' },
  { file: 'audio/clothe.mp3', english: 'clothe', russian: 'облекать' },
  { file: 'audio/cloven, cleaved.mp3', english: 'cloven, cleaved', russian: 'раскалывать, прокладывать себе пут' },
  { file: 'audio/clung.mp3', english: 'clung', russian: 'цепляться' },
  { file: 'audio/come.mp3', english: 'come', russian: 'прийти' },
  { file: 'audio/cost, costed.mp3', english: 'cost, costed', russian: 'стоить' },
  { file: 'audio/cost.mp3', english: 'cost', russian: 'стоить' },
  { file: 'audio/creep.mp3', english: 'creep', russian: 'ползти' },
  { file: 'audio/crept, crope.mp3', english: 'crept, crope', russian: 'ползти' },
  { file: 'audio/crept, cropen.mp3', english: 'crept, cropen', russian: 'ползти' },
  { file: 'audio/crew, crowed.mp3', english: 'crew, crowed', russian: 'кукарекать' },
  { file: 'audio/crow.mp3', english: 'crow', russian: 'кукарекать' },
  { file: 'audio/crown, crowed.mp3', english: 'crown, crowed', russian: '' },
  { file: 'audio/cut.mp3', english: 'cut', russian: 'резать' },
  { file: 'audio/dare.mp3', english: 'dare', russian: 'дерзать, сметь' },
  { file: 'audio/deal.mp3', english: 'deal', russian: 'иметь дело' },
  { file: 'audio/dealt.mp3', english: 'dealt', russian: 'иметь дело' },
  { file: 'audio/did.mp3', english: 'did', russian: 'делать' },
  { file: 'audio/dig.mp3', english: 'dig', russian: 'копать' },
  { file: 'audio/dive.mp3', english: 'dive', russian: 'нырять, погружаться' },
  { file: 'audio/do.mp3', english: 'do', russian: 'делать' },
  { file: 'audio/done.mp3', english: 'done', russian: 'делать' },
  { file: 'audio/dove, dived.mp3', english: 'dove, dived', russian: 'нырять, погружаться' },
  { file: 'audio/drag.mp3', english: 'drag', russian: 'тащить' },
  { file: 'audio/drank.mp3', english: 'drank', russian: 'пить, выпить' },
  { file: 'audio/draw.mp3', english: 'draw', russian: 'тащить, рисовать' },
  { file: 'audio/drawn.mp3', english: 'drawn', russian: 'тащить, рисовать' },
  { file: 'audio/dress.mp3', english: 'dress', russian: 'одеваться' },
  { file: 'audio/drest, dressed.mp3', english: 'drest, dressed', russian: 'одеваться' },
  { file: 'audio/drew.mp3', english: 'drew', russian: 'тащить, рисовать' },
  { file: 'audio/drink.mp3', english: 'drink', russian: 'пить, выпить' },
  { file: 'audio/drive.mp3', english: 'drive', russian: 'гнать, ехать' },
  { file: 'audio/driven.mp3', english: 'driven', russian: 'гнать, ехать' },
  { file: 'audio/drove.mp3', english: 'drove', russian: 'гнать, ехать' },
  { file: 'audio/drug, dragged.mp3', english: 'drug, dragged', russian: '' },
  { file: 'audio/drunk.mp3', english: 'drunk', russian: 'пить, выпить' },
  { file: 'audio/dug.mp3', english: 'dug', russian: 'копать' },
  { file: 'audio/durst, dared.mp3', english: 'durst, dared', russian: 'дерзать, сметь' },
  { file: 'audio/dwell.mp3', english: 'dwell', russian: 'обитать, задерживаться' },
  { file: 'audio/dwelt, dwelled.mp3', english: 'dwelt, dwelled', russian: 'обитать, задерживаться' },
  { file: 'audio/eat.mp3', english: 'eat', russian: 'кушать, есть' },
  { file: 'audio/eaten.mp3', english: 'eaten', russian: 'кушать, есть' },
  { file: 'audio/fall.mp3', english: 'fall', russian: 'падать' },
  { file: 'audio/fallen.mp3', english: 'fallen', russian: 'падать' },
  { file: 'audio/fed.mp3', english: 'fed', russian: 'кормить' },
  { file: 'audio/feed.mp3', english: 'feed', russian: 'кормить' },
  { file: 'audio/feel.mp3', english: 'feel', russian: 'чувствовать' },
  { file: 'audio/fell.mp3', english: 'fell', russian: 'падать' },
  { file: 'audio/felt.mp3', english: 'felt', russian: 'чувствовать' },
  { file: 'audio/fight.mp3', english: 'fight', russian: 'сражаться' },
  { file: 'audio/find.mp3', english: 'find', russian: 'находить' },
  { file: 'audio/fit, fitted.mp3', english: 'fit, fitted', russian: 'соответствовать, приспосабливаться' },
  { file: 'audio/fit.mp3', english: 'fit', russian: 'соответствовать, приспосабливаться' },
  { file: 'audio/fled.mp3', english: 'fled', russian: 'бежать, спасаться' },
  { file: 'audio/flee.mp3', english: 'flee', russian: 'бежать, спасаться' },
  { file: 'audio/flew.mp3', english: 'flew', russian: 'летать' },
  { file: 'audio/fling.mp3', english: 'fling', russian: 'бросить' },
  { file: 'audio/flown.mp3', english: 'flown', russian: 'летать' },
  { file: 'audio/flung.mp3', english: 'flung', russian: 'бросить' },
  { file: 'audio/fly.mp3', english: 'fly', russian: 'летать' },
  { file: 'audio/forbade.mp3', english: 'forbade', russian: 'запретить' },
  { file: 'audio/forbid.mp3', english: 'forbid', russian: 'запретить' },
  { file: 'audio/forbidden.mp3', english: 'forbidden', russian: 'запретить' },
  { file: 'audio/forgave.mp3', english: 'forgave', russian: 'простить' },
  { file: 'audio/forget.mp3', english: 'forget', russian: 'забыть' },
  { file: 'audio/forgive.mp3', english: 'forgive', russian: 'простить' },
  { file: 'audio/forgiven.mp3', english: 'forgiven', russian: 'простить' },
  { file: 'audio/forgot.mp3', english: 'forgot', russian: 'забыть' },
  { file: 'audio/forgotten.mp3', english: 'forgotten', russian: 'забыть' },
  { file: 'audio/forsake.mp3', english: 'forsake', russian: 'оставлять' },
  { file: 'audio/forsaken.mp3', english: 'forsaken', russian: 'оставлять' },
  { file: 'audio/forsook.mp3', english: 'forsook', russian: 'оставлять' },
  { file: 'audio/found.mp3', english: 'found', russian: 'находить' },
  { file: 'audio/freeze.mp3', english: 'freeze', russian: 'замерзнуть, замораживать' },
  { file: 'audio/froze.mp3', english: 'froze', russian: 'замерзнуть, замораживать' },
  { file: 'audio/frozen.mp3', english: 'frozen', russian: 'замерзнуть, замораживать' },
  { file: 'audio/gave.mp3', english: 'gave', russian: 'дать' },
  { file: 'audio/get.mp3', english: 'get', russian: 'получить' },
  { file: 'audio/gild.mp3', english: 'gild', russian: 'золотить' },
  { file: 'audio/gilt, gilded.mp3', english: 'gilt, gilded', russian: 'золотить' },
  { file: 'audio/gird.mp3', english: 'gird', russian: 'подпоясываться,подпоясывать' },
  { file: 'audio/girt, girded.mp3', english: 'girt, girded', russian: 'подпоясываться,подпоясывать' },
  { file: 'audio/give.mp3', english: 'give', russian: 'дать' },
  { file: 'audio/given.mp3', english: 'given', russian: 'дать' },
  { file: 'audio/go.mp3', english: 'go', russian: 'идти, уходить' },
  { file: 'audio/gone.mp3', english: 'gone', russian: 'идти, уходить' },
  { file: 'audio/got, gotten.mp3', english: 'got, gotten', russian: 'получить' },
  { file: 'audio/got.mp3', english: 'got', russian: 'получить' },
  { file: 'audio/grew.mp3', english: 'grew', russian: 'расти' },
  { file: 'audio/grind.mp3', english: 'grind', russian: 'точить, молоть' },
  { file: 'audio/ground, grinded.mp3', english: 'ground, grinded', russian: 'точить, молоть' },
  { file: 'audio/grow.mp3', english: 'grow', russian: 'расти' },
  { file: 'audio/grown.mp3', english: 'grown', russian: 'расти' },
  { file: 'audio/had.mp3', english: 'had', russian: 'иметь' },
  { file: 'audio/hang.mp3', english: 'hang', russian: 'висеть, повесить' },
  { file: 'audio/have.mp3', english: 'have', russian: 'иметь' },
  { file: 'audio/hear.mp3', english: 'hear', russian: 'слышать' },
  { file: 'audio/heard.mp3', english: 'heard', russian: 'слышать' },
  { file: 'audio/heave.mp3', english: 'heave', russian: 'подымать(ся), подъём' },
  { file: 'audio/held.mp3', english: 'held', russian: 'держать' },
  { file: 'audio/hew, hewed.mp3', english: 'hew, hewed', russian: 'рубить' },
  { file: 'audio/hew.mp3', english: 'hew', russian: 'рубить' },
  { file: 'audio/hewn, hewed.mp3', english: 'hewn, hewed', russian: 'рубить' },
  { file: 'audio/hid.mp3', english: 'hid', russian: 'прятать(ся)' },
  { file: 'audio/hidden.mp3', english: 'hidden', russian: 'прятать(ся)' },
  { file: 'audio/hide.mp3', english: 'hide', russian: 'прятать(ся)' },
  { file: 'audio/hit.mp3', english: 'hit', russian: 'ударить, попасть' },
  { file: 'audio/hoist, hoisted.mp3', english: 'hoist, hoisted', russian: 'поднмать' },
  { file: 'audio/hoist.mp3', english: 'hoist', russian: 'поднмать' },
  { file: 'audio/hold.mp3', english: 'hold', russian: 'держать' },
  { file: 'audio/hove, heaved.mp3', english: 'hove, heaved', russian: 'подымать(ся), подъём' },
  { file: 'audio/hoven, heaved, hove.mp3', english: 'hoven, heaved, hove', russian: 'подымать(ся), подъём' },
  { file: 'audio/hung.mp3', english: 'hung', russian: 'висеть, повесить' },
  { file: 'audio/hurt.mp3', english: 'hurt', russian: 'причинить боль' },
  { file: 'audio/keep.mp3', english: 'keep', russian: 'хранить' },
  { file: 'audio/ken.mp3', english: 'ken', russian: 'знать' },
  { file: 'audio/kent, kenned.mp3', english: 'kent, kenned', russian: 'знать' },
  { file: 'audio/kept.mp3', english: 'kept', russian: 'хранить' },
  { file: 'audio/kneel.mp3', english: 'kneel', russian: 'становиться на колени' },
  { file: 'audio/knelt, kneeled.mp3', english: 'knelt, kneeled', russian: 'становиться на колени' },
  { file: 'audio/knew.mp3', english: 'knew', russian: 'знать' },
  { file: 'audio/knit, knitted.mp3', english: 'knit, knitted', russian: 'вязать' },
  { file: 'audio/knit.mp3', english: 'knit', russian: 'вязать' },
  { file: 'audio/know.mp3', english: 'know', russian: 'знать' },
  { file: 'audio/known.mp3', english: 'known', russian: 'знать' },
  { file: 'audio/lade.mp3', english: 'lade', russian: 'грузить' },
  { file: 'audio/laden, laded.mp3', english: 'laden, laded', russian: 'грузить,положить' },
  { file: 'audio/laid.mp3', english: 'laid', russian: 'класть, положить' },
  { file: 'audio/lain.mp3', english: 'lain', russian: 'лежать' },
  { file: 'audio/lay.mp3', english: 'lay', russian: 'класть, положить' },
  { file: 'audio/lead.mp3', english: 'lead', russian: 'вести' },
  { file: 'audio/lean.mp3', english: 'lean', russian: 'опереться, прислониться' },
  { file: 'audio/leant, leaned.mp3', english: 'leant, leaned', russian: 'опереться, прислониться' },
  { file: 'audio/leap.mp3', english: 'leap', russian: 'прыгать' },
  { file: 'audio/leapt, leaped.mp3', english: 'leapt, leaped', russian: 'прыгать' },
  { file: 'audio/learn.mp3', english: 'learn', russian: 'учить' },
  { file: 'audio/learnt, learned.mp3', english: 'learnt, learned', russian: 'учить' },
  { file: 'audio/leave.mp3', english: 'leave', russian: 'оставить' },
  { file: 'audio/led.mp3', english: 'led', russian: 'вести' },
  { file: 'audio/left.mp3', english: 'left', russian: 'оставить' },
  { file: 'audio/lend.mp3', english: 'lend', russian: 'одолжить' },
  { file: 'audio/lent.mp3', english: 'lent', russian: 'одолжить' },
  { file: 'audio/let.mp3', english: 'let', russian: 'пустить, дать' },
  { file: 'audio/lie.mp3', english: 'lie', russian: 'лежать' },
  { file: 'audio/light.mp3', english: 'light', russian: 'осветить' },
  { file: 'audio/lit.mp3', english: 'lit', russian: 'осветить' },
  { file: 'audio/lode, laded.mp3', english: 'lode, laded', russian: '' },
  { file: 'audio/lose.mp3', english: 'lose', russian: 'терять' },
  { file: 'audio/lost.mp3', english: 'lost', russian: 'терять' },
  { file: 'audio/made.mp3', english: 'made', russian: 'делать' },
  { file: 'audio/make.mp3', english: 'make', russian: 'делать' },
  { file: 'audio/mean.mp3', english: 'mean', russian: 'подразумевать' },
  { file: 'audio/meant.mp3', english: 'meant', russian: 'подразумевать' },
  { file: 'audio/meet.mp3', english: 'meet', russian: 'встретить' },
  { file: 'audio/melt.mp3', english: 'melt', russian: 'таять' },
  { file: 'audio/met.mp3', english: 'met', russian: 'встретить' },
  { file: 'audio/molt, melted.mp3', english: 'molt, melted', russian: 'таять' },
  { file: 'audio/molt, molted.mp3', english: 'molt, molted', russian: 'таять' },
  { file: 'audio/molten, melted.mp3', english: 'molten, melted', russian: 'таять' },
  { file: 'audio/mow.mp3', english: 'mow', russian: 'косить' },
  { file: 'audio/mowed.mp3', english: 'mowed', russian: 'косить' },
  { file: 'audio/mown, mowed.mp3', english: 'mown, mowed', russian: 'косить' },
  { file: 'audio/or.mp3', english: 'or', russian: 'или' },
  { file: 'audio/paid.mp3', english: 'paid', russian: 'платить' },
  { file: 'audio/pay.mp3', english: 'pay', russian: 'платить' },
  { file: 'audio/plead.mp3', english: 'plead', russian: 'умолять' },
  { file: 'audio/pled, pleaded.mp3', english: 'pled, pleaded', russian: 'умолять' },
  { file: 'audio/prove.mp3', english: 'prove', russian: 'доказывать' },
  { file: 'audio/proved.mp3', english: 'proved', russian: 'доказывать' },
  { file: 'audio/proven, proved.mp3', english: 'proven, proved', russian: 'доказывать' },
  { file: 'audio/put.mp3', english: 'put', russian: 'класть' },
  { file: 'audio/quit, quitted.mp3', english: 'quit, quitted', russian: 'покидать, оставлять' },
  { file: 'audio/quit.mp3', english: 'quit', russian: 'покидать, оставлять' },
  { file: 'audio/ran.mp3', english: 'ran', russian: 'бежать, течь' },
  { file: 'audio/rang.mp3', english: 'rang', russian: 'звонить' },
  { file: 'audio/read.mp3', english: 'read', russian: 'читать' },
  { file: 'audio/read2.mp3', english: 'read2', russian: 'читать' },
  { file: 'audio/rend.mp3', english: 'rend', russian: 'раздирать, отдирать' },
  { file: 'audio/rent.mp3', english: 'rent', russian: 'раздирать, отдирать' },
  { file: 'audio/rid, ridded.mp3', english: 'rid, ridded', russian: 'избавлять' },
  { file: 'audio/rid.mp3', english: 'rid', russian: 'избавлять' },
  { file: 'audio/ridden.mp3', english: 'ridden', russian: 'ездить верхом' },
  { file: 'audio/ride.mp3', english: 'ride', russian: 'ездить верхом' },
  { file: 'audio/ring.mp3', english: 'ring', russian: 'звонить' },
  { file: 'audio/rise.mp3', english: 'rise', russian: 'подняться' },
  { file: 'audio/risen.mp3', english: 'risen', russian: 'подняться' },
  { file: 'audio/rive.mp3', english: 'rive', russian: 'раскалываться' },
  { file: 'audio/riven, rived.mp3', english: 'riven, rived', russian: 'раскалываться' },
  { file: 'audio/rode.mp3', english: 'rode', russian: 'ездить верхом' },
  { file: 'audio/rose.mp3', english: 'rose', russian: 'подняться' },
  { file: 'audio/rove, rived.mp3', english: 'rove, rived', russian: 'раскалываться' },
  { file: 'audio/run.mp3', english: 'run', russian: 'бежать, течь' },
  { file: 'audio/rung.mp3', english: 'rung', russian: 'звонить' },
  { file: 'audio/said.mp3', english: 'said', russian: 'говорить, сказать' },
  { file: 'audio/sang.mp3', english: 'sang', russian: 'петь' },
  { file: 'audio/sank.mp3', english: 'sank', russian: 'опускаться, погружаться, тонуть' },
  { file: 'audio/sat.mp3', english: 'sat', russian: 'сидеть' },
  { file: 'audio/saw.mp3', english: 'saw', russian: 'видеть' },
  { file: 'audio/sawed.mp3', english: 'sawed', russian: 'пилить' },
  { file: 'audio/sawn, sawed.mp3', english: 'sawn, sawed', russian: 'пилить, пилить' },
  { file: 'audio/say.mp3', english: 'say', russian: 'говорить, сказать' },
  { file: 'audio/see.mp3', english: 'see', russian: 'видеть' },
  { file: 'audio/seek.mp3', english: 'seek', russian: 'искать' },
  { file: 'audio/seen.mp3', english: 'seen', russian: 'видеть' },
  { file: 'audio/seethe.mp3', english: 'seethe', russian: 'бурлить' },
  { file: 'audio/sell.mp3', english: 'sell', russian: 'продавать' },
  { file: 'audio/send.mp3', english: 'send', russian: 'послать' },
  { file: 'audio/sent.mp3', english: 'sent', russian: 'послать' },
  { file: 'audio/set.mp3', english: 'set', russian: 'устанавливать' },
  { file: 'audio/sew.mp3', english: 'sew', russian: 'шить' },
  { file: 'audio/sewed.mp3', english: 'sewed', russian: 'шить' },
  { file: 'audio/sewn, sewed, sewen.mp3', english: 'sewn, sewed, sewen', russian: 'шить, шить' },
  { file: 'audio/shake.mp3', english: 'shake', russian: 'трясти' },
  { file: 'audio/shaken.mp3', english: 'shaken', russian: 'трясти' },
  { file: 'audio/shave.mp3', english: 'shave', russian: 'побриться, брить' },
  { file: 'audio/shaved.mp3', english: 'shaved', russian: 'побриться, брить' },
  { file: 'audio/shaven.mp3', english: 'shaven', russian: 'побриться, брить' },
];
