const data = [
  { file: 'audio/swim.mp3', english: 'swim', russian: 'плавать' },
  { file: 'audio/wrote.mp3', english: 'wrote', russian: 'написал' },
  { file: 'audio/flew.mp3', english: 'flew', russian: 'летал' },
  // добавь остальные
  { file: 'audio/stride.mp3', english: 'stride', russian: 'шагать' },
  { file: 'audio/strike.mp3', english: 'strike', russian: 'ударять' },
  { file: 'audio/string.mp3', english: 'string', russian: 'натягивать' },
  { file: 'audio/strip.mp3', english: 'strip', russian: 'раздевать' },
  { file: 'audio/stript, stripped.mp3', english: 'stript, stripped', russian: '' },
  { file: 'audio/strive.mp3', english: 'strive', russian: 'стремиться' },
  { file: 'audio/striven, strived.mp3', english: 'striven, strived', russian: '' },
  { file: 'audio/strode, strided.mp3', english: 'strode, strided', russian: '' },
  { file: 'audio/strove, strived.mp3', english: 'strove, strived', russian: 'стремился' },
  { file: 'audio/struck, stricken.mp3', english: 'struck, stricken', russian: 'ударил' },
  { file: 'audio/struck.mp3', english: 'struck', russian: 'ударил' },
  { file: 'audio/strung, stringed.mp3', english: 'strung, stringed', russian: 'натягивал' },
  { file: 'audio/stuck, sticked.mp3', english: 'stuck, sticked', russian: 'приклеивал' },
  { file: 'audio/stung, stang.mp3', english: 'stung, stang', russian: 'жалить' },
  { file: 'audio/stung.mp3', english: 'stung', russian: 'жалить' },
  { file: 'audio/stunk.mp3', english: 'stunk', russian: 'вонять' },
  { file: 'audio/sung.mp3', english: 'sung', russian: 'петь' },
  { file: 'audio/sunk.mp3', english: 'sunk', russian: 'тонуть' },
  { file: 'audio/swam.mp3', english: 'swam', russian: '' },
  { file: 'audio/swang.mp3', english: 'swang', russian: 'качаться' },
  { file: 'audio/swear.mp3', english: 'swear', russian: 'клясться' },
  { file: 'audio/sweat, sweated.mp3', english: 'sweat, sweated', russian: 'потеть' },
  { file: 'audio/sweat.mp3', english: 'sweat', russian: 'потеть' },
  { file: 'audio/sweep.mp3', english: 'sweep', russian: 'подметать' },
  { file: 'audio/swell.mp3', english: 'swell', russian: 'опухать' },
  { file: 'audio/swelt, swole, swoll, swelled.mp3', english: 'swelt, swole, swoll, swelled', russian: 'опухать' },
  { file: 'audio/swelt.mp3', english: 'swelt', russian: 'опухать' },
  { file: 'audio/swept, sweeped.mp3', english: 'swept, sweeped', russian: 'подмел' },
  { file: 'audio/swim.mp3', english: 'swim', russian: 'плавать' },
  { file: 'audio/swing.mp3', english: 'swing', russian: 'качаться' },
  { file: 'audio/swollen, swelled.mp3', english: 'swollen, swelled', russian: 'опухший' },
  { file: 'audio/swore.mp3', english: 'swore', russian: 'поклялся' },
  { file: 'audio/sworn.mp3', english: 'sworn', russian: 'поклявшийся' },
  { file: 'audio/swum.mp3', english: 'swum', russian: 'плавал' },
  { file: 'audio/swung.mp3', english: 'swung', russian: 'качался' },
  { file: 'audio/take.mp3', english: 'take', russian: 'брать' },
  { file: 'audio/taken.mp3', english: 'taken', russian: 'взятый' },
  { file: 'audio/taught.mp3', english: 'taught', russian: 'учил' },
  { file: 'audio/teach.mp3', english: 'teach', russian: 'учить' },
  { file: 'audio/tear.mp3', english: 'tear', russian: 'рвать' },
  { file: 'audio/tell.mp3', english: 'tell', russian: 'рассказывать' },
  { file: 'audio/think.mp3', english: 'think', russian: 'думать' },
  { file: 'audio/thought.mp3', english: 'thought', russian: 'думал' },
  { file: 'audio/threw.mp3', english: 'threw', russian: 'бросил' },
  { file: 'audio/thrive.mp3', english: 'thrive', russian: '' },
  { file: 'audio/thriven, thrived.mp3', english: 'thriven, thrived', russian: '' },
  { file: 'audio/throve, thrived, thrave.mp3', english: 'throve, thrived, thrave', russian: '' },
  { file: 'audio/throve, thrived.mp3', english: 'throve, thrived', russian: '' },
  { file: 'audio/throw.mp3', english: 'throw', russian: 'бросать' },
  { file: 'audio/thrown.mp3', english: 'thrown', russian: 'брошенный' },
  { file: 'audio/thrust, thrusted.mp3', english: 'thrust, thrusted', russian: '' },
  { file: 'audio/thrust.mp3', english: 'thrust', russian: '' },
  { file: 'audio/told.mp3', english: 'told', russian: 'рассказал' },
  { file: 'audio/took.mp3', english: 'took', russian: 'взял' },
  { file: 'audio/tore.mp3', english: 'tore', russian: 'порвал' },
  { file: 'audio/torn.mp3', english: 'torn', russian: 'порванный' },
  { file: 'audio/understand.mp3', english: 'understand', russian: 'понимать' },
  { file: 'audio/understood.mp3', english: 'understood', russian: 'понял' },
  { file: 'audio/vex.mp3', english: 'vex', russian: '' },
  { file: 'audio/vext, vexed.mp3', english: 'vext, vexed', russian: '' },
  { file: 'audio/wake.mp3', english: 'wake', russian: 'просыпаться' },
  { file: 'audio/was, were.mp3', english: 'was, were', russian: 'был' },
  { file: 'audio/wax.mp3', english: 'wax', russian: '' },
  { file: 'audio/waxen, waxed.mp3', english: 'waxen, waxed', russian: '' },
  { file: 'audio/wear.mp3', english: 'wear', russian: 'носить' },
  { file: 'audio/weave.mp3', english: 'weave', russian: '' },
  { file: 'audio/wed, wedded.mp3', english: 'wed, wedded', russian: '' },
  { file: 'audio/wed.mp3', english: 'wed', russian: '' },
  { file: 'audio/weep.mp3', english: 'weep', russian: '' },
  { file: 'audio/wend.mp3', english: 'wend', russian: '' },
  { file: 'audio/went, wended.mp3', english: 'went, wended', russian: 'пошел' },
  { file: 'audio/went.mp3', english: 'went', russian: 'пошел' },
  { file: 'audio/wept, weeped.mp3', english: 'wept, weeped', russian: '' },
  { file: 'audio/wet, wetted.mp3', english: 'wet, wetted', russian: '' },
  { file: 'audio/wet.mp3', english: 'wet', russian: '' },
  { file: 'audio/wex, waxed.mp3', english: 'wex, waxed', russian: '' },
  { file: 'audio/win.mp3', english: 'win', russian: '' },
  { file: 'audio/wind.mp3', english: 'wind', russian: '' },
  { file: 'audio/woke.mp3', english: 'woke', russian: '' },
  { file: 'audio/woken.mp3', english: 'woken', russian: '' },
  { file: 'audio/won.mp3', english: 'won', russian: 'выиграл' },
  { file: 'audio/wore.mp3', english: 'wore', russian: '' },
  { file: 'audio/worn.mp3', english: 'worn', russian: '' },
  { file: 'audio/wound.mp3', english: 'wound', russian: '' },
  { file: 'audio/wove.mp3', english: 'wove', russian: '' },
  { file: 'audio/woven.mp3', english: 'woven', russian: '' },
  { file: 'audio/wrang, wrung, wringed.mp3', english: 'wrang, wrung, wringed', russian: '' },
  { file: 'audio/wreak.mp3', english: 'wreak', russian: '' },
  { file: 'audio/wring.mp3', english: 'wring', russian: '' },
  { file: 'audio/write.mp3', english: 'write', russian: 'писать' },
  { file: 'audio/writhe.mp3', english: 'writhe', russian: '' },
  { file: 'audio/writhen, writhed.mp3', english: 'writhen, writhed', russian: '' },
  { file: 'audio/written.mp3', english: 'written', russian: 'написанный' },
  { file: 'audio/wroke, wreaked.mp3', english: 'wroke, wreaked', russian: '' },
  { file: 'audio/wroken, wreaked.mp3', english: 'wroken, wreaked', russian: '' },
  { file: 'audio/wrote.mp3', english: 'wrote', russian: 'написал' },
  { file: 'audio/wrothe, writhed.mp3', english: 'wrothe, writhed', russian: '' },
  { file: 'audio/wrung, wringed.mp3', english: 'wrung, wringed', russian: '' },
  { file: 'audio/ate.mp3', english: 'ate', russian: 'ел' },
  { file: 'audio/be (am, is, are).mp3', english: 'be (am, is, are)', russian: 'быть' },
  { file: 'audio/bear.mp3', english: 'bear', russian: '' },
  { file: 'audio/beat.mp3', english: 'beat', russian: '' },
  { file: 'audio/beaten.mp3', english: 'beaten', russian: '' },
  { file: 'audio/became.mp3', english: 'became', russian: '' },
  { file: 'audio/become.mp3', english: 'become', russian: '' },
  { file: 'audio/been.mp3', english: 'been', russian: '' },
  { file: 'audio/began.mp3', english: 'began', russian: '' },
  { file: 'audio/beget.mp3', english: 'beget', russian: '' },
  { file: 'audio/begin.mp3', english: 'begin', russian: '' },
  { file: 'audio/begot.mp3', english: 'begot', russian: '' },
  { file: 'audio/begotten.mp3', english: 'begotten', russian: '' },
  { file: 'audio/begun.mp3', english: 'begun', russian: '' },
  { file: 'audio/bend.mp3', english: 'bend', russian: '' },
  { file: 'audio/bent.mp3', english: 'bent', russian: '' },
  { file: 'audio/bereave.mp3', english: 'bereave', russian: '' },
  { file: 'audio/bereft, bereaved.mp3', english: 'bereft, bereaved', russian: '' },
  { file: 'audio/beseech.mp3', english: 'beseech', russian: '' },
  { file: 'audio/besought, beseeched.mp3', english: 'besought, beseeched', russian: '' },
  { file: 'audio/bet.mp3', english: 'bet', russian: '' },
  { file: 'audio/bid.mp3', english: 'bid', russian: '' },
  { file: 'audio/bidden, bided.mp3', english: 'bidden, bided', russian: '' },
  { file: 'audio/bide.mp3', english: 'bide', russian: '' },
  { file: 'audio/bind.mp3', english: 'bind', russian: '' },
  { file: 'audio/bit.mp3', english: 'bit', russian: '' },
  { file: 'audio/bite.mp3', english: 'bite', russian: '' },
  { file: 'audio/bitten.mp3', english: 'bitten', russian: '' },
  { file: 'audio/bled.mp3', english: 'bled', russian: '' },
  { file: 'audio/bleed.mp3', english: 'bleed', russian: '' },
  { file: 'audio/blew.mp3', english: 'blew', russian: '' },
  { file: 'audio/blow.mp3', english: 'blow', russian: '' },
  { file: 'audio/blown.mp3', english: 'blown', russian: '' },
  { file: 'audio/bode, bided.mp3', english: 'bode, bided', russian: '' },
  { file: 'audio/bore.mp3', english: 'bore', russian: '' },
  { file: 'audio/born, borne.mp3', english: 'born, borne', russian: '' },
  { file: 'audio/bought.mp3', english: 'bought', russian: 'купил' },
  { file: 'audio/bound.mp3', english: 'bound', russian: '' },
  { file: 'audio/break.mp3', english: 'break', russian: '' },
  { file: 'audio/bred.mp3', english: 'bred', russian: '' },
  { file: 'audio/breed.mp3', english: 'breed', russian: '' },
  { file: 'audio/bring.mp3', english: 'bring', russian: '' },
  { file: 'audio/broadcast, broadcasted.mp3', english: 'broadcast, broadcasted', russian: '' },
  { file: 'audio/broadcast.mp3', english: 'broadcast', russian: '' },
  { file: 'audio/broke.mp3', english: 'broke', russian: '' },
  { file: 'audio/broken.mp3', english: 'broken', russian: '' },
  { file: 'audio/brought.mp3', english: 'brought', russian: '' },
  { file: 'audio/build.mp3', english: 'build', russian: '' },
  { file: 'audio/built.mp3', english: 'built', russian: '' },
  { file: 'audio/burn.mp3', english: 'burn', russian: '' },
  { file: 'audio/burnt, burned.mp3', english: 'burnt, burned', russian: '' },
  { file: 'audio/burst.mp3', english: 'burst', russian: '' },
  { file: 'audio/bust, busted.mp3', english: 'bust, busted', russian: '' },
  { file: 'audio/bust.mp3', english: 'bust', russian: '' },
  { file: 'audio/buy.mp3', english: 'buy', russian: 'покупать' },
  { file: 'audio/came.mp3', english: 'came', russian: '' },
  { file: 'audio/cast.mp3', english: 'cast', russian: '' },
  { file: 'audio/catch.mp3', english: 'catch', russian: '' },
  { file: 'audio/caught.mp3', english: 'caught', russian: '' },
  { file: 'audio/chid, chided.mp3', english: 'chid, chided', russian: '' },
  { file: 'audio/chidden, chided, chid.mp3', english: 'chidden, chided, chid', russian: '' },
  { file: 'audio/chide.mp3', english: 'chide', russian: '' },
  { file: 'audio/choose.mp3', english: 'choose', russian: '' },
  { file: 'audio/chose.mp3', english: 'chose', russian: '' },
  { file: 'audio/chosen.mp3', english: 'chosen', russian: '' },
  { file: 'audio/clad, clothed.mp3', english: 'clad, clothed', russian: '' },
  { file: 'audio/clad.mp3', english: 'clad', russian: '' },
  { file: 'audio/clap.mp3', english: 'clap', russian: '' },
  { file: 'audio/clapt, clapped.mp3', english: 'clapt, clapped', russian: '' },
  { file: 'audio/cleave.mp3', english: 'cleave', russian: '' },
  { file: 'audio/cleft, cleaved.mp3', english: 'cleft, cleaved', russian: '' },
  { file: 'audio/cling.mp3', english: 'cling', russian: '' },
  { file: 'audio/clothe.mp3', english: 'clothe', russian: '' },
  { file: 'audio/cloven, cleaved.mp3', english: 'cloven, cleaved', russian: '' },
  { file: 'audio/clung.mp3', english: 'clung', russian: '' },
  { file: 'audio/come.mp3', english: 'come', russian: '' },
  { file: 'audio/cost, costed.mp3', english: 'cost, costed', russian: '' },
  { file: 'audio/cost.mp3', english: 'cost', russian: '' },
  { file: 'audio/creep.mp3', english: 'creep', russian: '' },
  { file: 'audio/crept, crope.mp3', english: 'crept, crope', russian: '' },
  { file: 'audio/crept, cropen.mp3', english: 'crept, cropen', russian: '' },
  { file: 'audio/crew, crowed.mp3', english: 'crew, crowed', russian: '' },
  { file: 'audio/crow.mp3', english: 'crow', russian: '' },
  { file: 'audio/crown, crowed.mp3', english: 'crown, crowed', russian: '' },
  { file: 'audio/cut.mp3', english: 'cut', russian: '' },
  { file: 'audio/dare.mp3', english: 'dare', russian: '' },
  { file: 'audio/deal.mp3', english: 'deal', russian: '' },
  { file: 'audio/dealt.mp3', english: 'dealt', russian: '' },
  { file: 'audio/did.mp3', english: 'did', russian: 'сделал' },
  { file: 'audio/dig.mp3', english: 'dig', russian: '' },
  { file: 'audio/dive.mp3', english: 'dive', russian: '' },
  { file: 'audio/do.mp3', english: 'do', russian: 'делать' },
  { file: 'audio/done.mp3', english: 'done', russian: 'сделанный' },
  { file: 'audio/dove, dived.mp3', english: 'dove, dived', russian: '' },
  { file: 'audio/drag.mp3', english: 'drag', russian: '' },
  { file: 'audio/drank.mp3', english: 'drank', russian: 'пил' },
  { file: 'audio/draw.mp3', english: 'draw', russian: '' },
  { file: 'audio/drawn.mp3', english: 'drawn', russian: '' },
  { file: 'audio/dress.mp3', english: 'dress', russian: '' },
  { file: 'audio/drest, dressed.mp3', english: 'drest, dressed', russian: '' },
  { file: 'audio/drew.mp3', english: 'drew', russian: '' },
  { file: 'audio/drink.mp3', english: 'drink', russian: 'пить' },
  { file: 'audio/drive.mp3', english: 'drive', russian: '' },
  { file: 'audio/driven.mp3', english: 'driven', russian: '' },
  { file: 'audio/drove.mp3', english: 'drove', russian: '' },
  { file: 'audio/drug, dragged.mp3', english: 'drug, dragged', russian: '' },
  { file: 'audio/drunk.mp3', english: 'drunk', russian: 'выпитый' },
  { file: 'audio/dug.mp3', english: 'dug', russian: '' },
  { file: 'audio/durst, dared.mp3', english: 'durst, dared', russian: '' },
  { file: 'audio/dwell.mp3', english: 'dwell', russian: '' },
  { file: 'audio/dwelt, dwelled.mp3', english: 'dwelt, dwelled', russian: '' },
  { file: 'audio/eat.mp3', english: 'eat', russian: 'есть' },
  { file: 'audio/eaten.mp3', english: 'eaten', russian: 'съеденный' },
  { file: 'audio/fall.mp3', english: 'fall', russian: '' },
  { file: 'audio/fallen.mp3', english: 'fallen', russian: '' },
  { file: 'audio/fed.mp3', english: 'fed', russian: '' },
  { file: 'audio/feed.mp3', english: 'feed', russian: '' },
  { file: 'audio/feel.mp3', english: 'feel', russian: '' },
  { file: 'audio/fell.mp3', english: 'fell', russian: '' },
  { file: 'audio/felt.mp3', english: 'felt', russian: '' },
  { file: 'audio/fight.mp3', english: 'fight', russian: '' },
  { file: 'audio/find.mp3', english: 'find', russian: '' },
  { file: 'audio/fit, fitted.mp3', english: 'fit, fitted', russian: '' },
  { file: 'audio/fit.mp3', english: 'fit', russian: '' },
  { file: 'audio/fled.mp3', english: 'fled', russian: '' },
  { file: 'audio/flee.mp3', english: 'flee', russian: '' },
  { file: 'audio/flew.mp3', english: 'flew', russian: 'летал' },
  { file: 'audio/fling.mp3', english: 'fling', russian: '' },
  { file: 'audio/flown.mp3', english: 'flown', russian: '' },
  { file: 'audio/flung.mp3', english: 'flung', russian: '' },
  { file: 'audio/fly.mp3', english: 'fly', russian: '' },
  { file: 'audio/forbade.mp3', english: 'forbade', russian: '' },
  { file: 'audio/forbid.mp3', english: 'forbid', russian: '' },
  { file: 'audio/forbidden.mp3', english: 'forbidden', russian: '' },
  { file: 'audio/forgave.mp3', english: 'forgave', russian: '' },
  { file: 'audio/forget.mp3', english: 'forget', russian: '' },
  { file: 'audio/forgive.mp3', english: 'forgive', russian: '' },
  { file: 'audio/forgiven.mp3', english: 'forgiven', russian: '' },
  { file: 'audio/forgot.mp3', english: 'forgot', russian: '' },
  { file: 'audio/forgotten.mp3', english: 'forgotten', russian: '' },
  { file: 'audio/forsake.mp3', english: 'forsake', russian: '' },
  { file: 'audio/forsaken.mp3', english: 'forsaken', russian: '' },
  { file: 'audio/forsook.mp3', english: 'forsook', russian: '' },
  { file: 'audio/found.mp3', english: 'found', russian: '' },
  { file: 'audio/freeze.mp3', english: 'freeze', russian: '' },
  { file: 'audio/froze.mp3', english: 'froze', russian: '' },
  { file: 'audio/frozen.mp3', english: 'frozen', russian: '' },
  { file: 'audio/gave.mp3', english: 'gave', russian: '' },
  { file: 'audio/get.mp3', english: 'get', russian: '' },
  { file: 'audio/gild.mp3', english: 'gild', russian: '' },
  { file: 'audio/gilt, gilded.mp3', english: 'gilt, gilded', russian: '' },
  { file: 'audio/gird.mp3', english: 'gird', russian: '' },
  { file: 'audio/girt, girded.mp3', english: 'girt, girded', russian: '' },
  { file: 'audio/give.mp3', english: 'give', russian: '' },
  { file: 'audio/given.mp3', english: 'given', russian: '' },
  { file: 'audio/go.mp3', english: 'go', russian: 'идти' },
  { file: 'audio/gone.mp3', english: 'gone', russian: 'ушел' },
  { file: 'audio/got, gotten.mp3', english: 'got, gotten', russian: '' },
  { file: 'audio/got.mp3', english: 'got', russian: '' },
  { file: 'audio/grew.mp3', english: 'grew', russian: '' },
  { file: 'audio/grind.mp3', english: 'grind', russian: '' },
  { file: 'audio/ground, grinded.mp3', english: 'ground, grinded', russian: '' },
  { file: 'audio/grow.mp3', english: 'grow', russian: '' },
  { file: 'audio/grown.mp3', english: 'grown', russian: '' },
  { file: 'audio/had.mp3', english: 'had', russian: '' },
  { file: 'audio/hang.mp3', english: 'hang', russian: '' },
  { file: 'audio/have.mp3', english: 'have', russian: '' },
  { file: 'audio/hear.mp3', english: 'hear', russian: '' },
  { file: 'audio/heard.mp3', english: 'heard', russian: '' },
  { file: 'audio/heave.mp3', english: 'heave', russian: '' },
  { file: 'audio/held.mp3', english: 'held', russian: '' },
  { file: 'audio/hew, hewed.mp3', english: 'hew, hewed', russian: '' },
  { file: 'audio/hew.mp3', english: 'hew', russian: '' },
  { file: 'audio/hewn, hewed.mp3', english: 'hewn, hewed', russian: '' },
  { file: 'audio/hid.mp3', english: 'hid', russian: '' },
  { file: 'audio/hidden.mp3', english: 'hidden', russian: '' },
  { file: 'audio/hide.mp3', english: 'hide', russian: '' },
  { file: 'audio/hit.mp3', english: 'hit', russian: '' },
  { file: 'audio/hoist, hoisted.mp3', english: 'hoist, hoisted', russian: '' },
  { file: 'audio/hoist.mp3', english: 'hoist', russian: '' },
  { file: 'audio/hold.mp3', english: 'hold', russian: '' },
  { file: 'audio/hove, heaved.mp3', english: 'hove, heaved', russian: '' },
  { file: 'audio/hoven, heaved, hove.mp3', english: 'hoven, heaved, hove', russian: '' },
  { file: 'audio/hung.mp3', english: 'hung', russian: '' },
  { file: 'audio/hurt.mp3', english: 'hurt', russian: '' },
  { file: 'audio/keep.mp3', english: 'keep', russian: '' },
  { file: 'audio/ken.mp3', english: 'ken', russian: '' },
  { file: 'audio/kent, kenned.mp3', english: 'kent, kenned', russian: '' },
  { file: 'audio/kept.mp3', english: 'kept', russian: '' },
  { file: 'audio/kneel.mp3', english: 'kneel', russian: '' },
  { file: 'audio/knelt, kneeled.mp3', english: 'knelt, kneeled', russian: '' },
  { file: 'audio/knew.mp3', english: 'knew', russian: '' },
  { file: 'audio/knit, knitted.mp3', english: 'knit, knitted', russian: '' },
  { file: 'audio/knit.mp3', english: 'knit', russian: '' },
  { file: 'audio/know.mp3', english: 'know', russian: '' },
  { file: 'audio/known.mp3', english: 'known', russian: '' },
  { file: 'audio/lade.mp3', english: 'lade', russian: '' },
  { file: 'audio/laden, laded.mp3', english: 'laden, laded', russian: '' },
  { file: 'audio/laid.mp3', english: 'laid', russian: '' },
  { file: 'audio/lain.mp3', english: 'lain', russian: '' },
  { file: 'audio/lay.mp3', english: 'lay', russian: '' },
  { file: 'audio/lead.mp3', english: 'lead', russian: '' },
  { file: 'audio/lean.mp3', english: 'lean', russian: '' },
  { file: 'audio/leant, leaned.mp3', english: 'leant, leaned', russian: '' },
  { file: 'audio/leap.mp3', english: 'leap', russian: '' },
  { file: 'audio/leapt, leaped.mp3', english: 'leapt, leaped', russian: '' },
  { file: 'audio/learn.mp3', english: 'learn', russian: '' },
  { file: 'audio/learnt, learned.mp3', english: 'learnt, learned', russian: '' },
  { file: 'audio/leave.mp3', english: 'leave', russian: '' },
  { file: 'audio/led.mp3', english: 'led', russian: '' },
  { file: 'audio/left.mp3', english: 'left', russian: '' },
  { file: 'audio/lend.mp3', english: 'lend', russian: '' },
  { file: 'audio/lent.mp3', english: 'lent', russian: '' },
  { file: 'audio/let.mp3', english: 'let', russian: '' },
  { file: 'audio/lie.mp3', english: 'lie', russian: '' },
  { file: 'audio/light.mp3', english: 'light', russian: '' },
  { file: 'audio/lit.mp3', english: 'lit', russian: '' },
  { file: 'audio/lode, laded.mp3', english: 'lode, laded', russian: '' },
  { file: 'audio/lose.mp3', english: 'lose', russian: '' },
  { file: 'audio/lost.mp3', english: 'lost', russian: '' },
  { file: 'audio/made.mp3', english: 'made', russian: 'сделал' },
  { file: 'audio/make.mp3', english: 'make', russian: 'делать' },
  { file: 'audio/mean.mp3', english: 'mean', russian: '' },
  { file: 'audio/meant.mp3', english: 'meant', russian: '' },
  { file: 'audio/meet.mp3', english: 'meet', russian: '' },
  { file: 'audio/melt.mp3', english: 'melt', russian: '' },
  { file: 'audio/met.mp3', english: 'met', russian: '' },
  { file: 'audio/molt, melted.mp3', english: 'molt, melted', russian: '' },
  { file: 'audio/molt, molted.mp3', english: 'molt, molted', russian: '' },
  { file: 'audio/molten, melted.mp3', english: 'molten, melted', russian: '' },
  { file: 'audio/mow.mp3', english: 'mow', russian: '' },
  { file: 'audio/mowed.mp3', english: 'mowed', russian: '' },
  { file: 'audio/mown, mowed.mp3', english: 'mown, mowed', russian: '' },
  { file: 'audio/or.mp3', english: 'or', russian: '' },
  { file: 'audio/paid.mp3', english: 'paid', russian: '' },
  { file: 'audio/pay.mp3', english: 'pay', russian: '' },
  { file: 'audio/plead.mp3', english: 'plead', russian: '' },
  { file: 'audio/pled, pleaded.mp3', english: 'pled, pleaded', russian: '' },
  { file: 'audio/prove.mp3', english: 'prove', russian: '' },
  { file: 'audio/proved.mp3', english: 'proved', russian: '' },
  { file: 'audio/proven, proved.mp3', english: 'proven, proved', russian: '' },
  { file: 'audio/put.mp3', english: 'put', russian: '' },
  { file: 'audio/quit, quitted.mp3', english: 'quit, quitted', russian: '' },
  { file: 'audio/quit.mp3', english: 'quit', russian: '' },
  { file: 'audio/ran.mp3', english: 'ran', russian: 'бежал' },
  { file: 'audio/rang.mp3', english: 'rang', russian: '' },
  { file: 'audio/read.mp3', english: 'read', russian: '' },
  { file: 'audio/read2.mp3', english: 'read2', russian: '' },
  { file: 'audio/rend.mp3', english: 'rend', russian: '' },
  { file: 'audio/rent.mp3', english: 'rent', russian: '' },
  { file: 'audio/rid, ridded.mp3', english: 'rid, ridded', russian: '' },
  { file: 'audio/rid.mp3', english: 'rid', russian: '' },
  { file: 'audio/ridden.mp3', english: 'ridden', russian: '' },
  { file: 'audio/ride.mp3', english: 'ride', russian: '' },
  { file: 'audio/ring.mp3', english: 'ring', russian: '' },
  { file: 'audio/rise.mp3', english: 'rise', russian: '' },
  { file: 'audio/risen.mp3', english: 'risen', russian: '' },
  { file: 'audio/rive.mp3', english: 'rive', russian: '' },
  { file: 'audio/riven, rived.mp3', english: 'riven, rived', russian: '' },
  { file: 'audio/rode.mp3', english: 'rode', russian: '' },
  { file: 'audio/rose.mp3', english: 'rose', russian: '' },
  { file: 'audio/rove, rived.mp3', english: 'rove, rived', russian: '' },
  { file: 'audio/run.mp3', english: 'run', russian: 'бежать' },
  { file: 'audio/rung.mp3', english: 'rung', russian: '' },
  { file: 'audio/said.mp3', english: 'said', russian: 'сказал' },
  { file: 'audio/sang.mp3', english: 'sang', russian: '' },
  { file: 'audio/sank.mp3', english: 'sank', russian: '' },
  { file: 'audio/sat.mp3', english: 'sat', russian: '' },
  { file: 'audio/saw.mp3', english: 'saw', russian: 'увидел' },
  { file: 'audio/sawed.mp3', english: 'sawed', russian: '' },
  { file: 'audio/sawn, sawed.mp3', english: 'sawn, sawed', russian: '' },
  { file: 'audio/say.mp3', english: 'say', russian: 'сказать' },
  { file: 'audio/see.mp3', english: 'see', russian: 'видеть' },
  { file: 'audio/seek.mp3', english: 'seek', russian: '' },
  { file: 'audio/seen.mp3', english: 'seen', russian: 'увиденный' },
  { file: 'audio/seethe.mp3', english: 'seethe', russian: '' },
  { file: 'audio/sell.mp3', english: 'sell', russian: '' },
  { file: 'audio/send.mp3', english: 'send', russian: '' },
  { file: 'audio/sent.mp3', english: 'sent', russian: '' },
  { file: 'audio/set.mp3', english: 'set', russian: '' },
  { file: 'audio/sew.mp3', english: 'sew', russian: '' },
  { file: 'audio/sewed.mp3', english: 'sewed', russian: '' },
  { file: 'audio/sewn, sewed, sewen.mp3', english: 'sewn, sewed, sewen', russian: '' },
  { file: 'audio/shake.mp3', english: 'shake', russian: '' },
  { file: 'audio/shaken.mp3', english: 'shaken', russian: '' },
  { file: 'audio/shave.mp3', english: 'shave', russian: '' },
  { file: 'audio/shaved.mp3', english: 'shaved', russian: '' },
  { file: 'audio/shaven.mp3', english: 'shaven', russian: '' }

  
];
